[build]
	command = "npm run build"
	publish = ".next"
	functions = ".netlify/functions"

[[redirects]]
	from ="/*"
	to ="/index.html"
	status = 200

[[plugins]]
	package = "@netlify/plugin-nextjs"

[build.environment]
	NEXT_TELEMETRY_DISABLED = "1"

[context.production.environment]
	NODE_ENV="production"
	ESLINT_USE_FLAT_CONFIG="true"
	NEXT_PUBLIC_BASE_URL="https://songs-of-anhanga.netlify.app/"
